# Generated by Django 4.1.dev20211213175307 on 2022-02-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
