# Generated by Django 4.1.dev20211213175307 on 2022-02-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
