# Generated by Django 4.0 on 2022-02-17 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_created_at_order_is_ordered_order_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
